// Mirrors components/app/master_dashboard/dashboard-seed-data.ts
window.DASH_DATA = {
  metrics: [
    { label: "Tracked revenue",      value: "$24,810", detail: "+18% vs last 30d",         tone: "emerald", delta: "+$3,400" },
    { label: "Open opportunity value", value: "$11,200", detail: "Across 3 active leads",   tone: "blue",    delta: "3 leads" },
    { label: "Unpaid invoices",      value: "$2,400",  detail: "1 invoice past 7 days",    tone: "amber",   delta: "1 overdue" },
  ],
  activeProjects: [
    { name: "luis-ruiz.com Master Hub", status: "building",     next: "Continue feature-spec implementation loop" },
    { name: "ruizTechServices",         status: "active",       next: "Clarify services and lead intake path" },
    { name: "Nucleus",                  status: "product track",next: "Protect API product contract while dashboard work continues" },
    { name: "24HourGPT",                status: "paused",       next: "Revisit positioning after master hub foundation" },
  ],
  leads: [
    { name: "Selene Studio",   stage: "qualified",   value: "$6,400", note: "Booking site + Stripe; awaiting brand assets." },
    { name: "Bronx Med Group", stage: "contacted",   value: "$2,800", note: "Internal dashboard for patient intake notes." },
    { name: "Veronique LLC",   stage: "proposal sent", value: "$2,000", note: "Two-page launch + booking; sent Wed." },
  ],
  decisions: [
    { title: "Use luis-ruiz.com as the master hub",            status: "active", note: "Public site in front, owner command center behind it." },
    { title: "Keep dashboard data separate from public projects", status: "active", note: "Operational project records will come from later dashboard tables." },
    { title: "Protect existing AI and Nucleus surfaces",       status: "active", note: "Dashboard shell work should not rewrite product routes." },
  ],
  contentQueue: [
    { title: "Refactor notes — master hub", state: "in progress", target: "Fri" },
    { title: "Round-robin orchestration extraction", state: "draft", target: "Next week" },
    { title: "Nucleus credit accounting walkthrough", state: "outlined", target: "Two weeks" },
  ],
  aiTools: [
    { name: "Ollama Chat",   href: "/ollama",      status: "available", description: "Local-model chat with optional persistence and RAG." },
    { name: "Round-Robin",   href: "/round-robin", status: "available", description: "Multi-model discussion across providers." },
    { name: "Nucleus API",   href: "/api/nucleus", status: "protected", description: "Bearer-token API product with model catalog." },
    { name: "GitHub Snapshot", href: "#",          status: "owner tool", description: "Branch and repo activity view." },
  ],
  systemLinks: [
    { label: "luis-ruiz.com",     href: "/",                                          description: "Public master hub",        external: false },
    { label: "ruizTechServices",  href: "https://ruiztechservices.com",               description: "Business site",            external: true },
    { label: "Nucleus",           href: "/api/nucleus/models",                        description: "API product model endpoint", external: false },
    { label: "GitHub repo",       href: "https://github.com/ruizTechServices/luis_ruiz_2", description: "Source repository",     external: true },
    { label: "Supabase",          href: "https://supabase.com/dashboard",             description: "Database, auth, storage",  external: true },
    { label: "Vercel",            href: "https://vercel.com/dashboard",               description: "Deployments & settings",   external: true },
  ],
  health: [
    { name: "Supabase",     status: "operational", latency: "84 ms" },
    { name: "OpenAI",       status: "operational", latency: "210 ms" },
    { name: "Anthropic",    status: "operational", latency: "640 ms" },
    { name: "Ollama (local)", status: "degraded",  latency: "—" },
    { name: "Pinecone",     status: "operational", latency: "120 ms" },
    { name: "Stripe",       status: "operational", latency: "180 ms" },
  ],
};

window.DASH_STATUS_TONE = {
  "active":        { fg: "#22C55E", bg: "rgba(34,197,94,0.12)"   },
  "paused":        { fg: "#EAB308", bg: "rgba(234,179,8,0.14)"   },
  "blocked":       { fg: "#EF4444", bg: "rgba(239,68,68,0.12)"   },
  "shipped":       { fg: "#38BDF8", bg: "rgba(56,189,248,0.14)"  },
  "testing":       { fg: "#A78BFA", bg: "rgba(167,139,250,0.14)" },
  "building":      { fg: "#5EEAD4", bg: "rgba(94,234,212,0.12)"  },
  "product track": { fg: "#A78BFA", bg: "rgba(167,139,250,0.14)" },
  "new":           { fg: "#5EEAD4", bg: "rgba(94,234,212,0.14)"  },
  "contacted":     { fg: "#38BDF8", bg: "rgba(56,189,248,0.14)"  },
  "qualified":     { fg: "#818CF8", bg: "rgba(129,140,248,0.14)" },
  "proposal sent": { fg: "#C084FC", bg: "rgba(192,132,252,0.14)" },
  "deposit paid":  { fg: "#34D399", bg: "rgba(52,211,153,0.14)"  },
  "in progress":   { fg: "#FBBF24", bg: "rgba(251,191,36,0.14)"  },
  "delivered":     { fg: "#22C55E", bg: "rgba(34,197,94,0.14)"   },
  "lost":          { fg: "#94A3B8", bg: "rgba(148,163,184,0.18)" },
  "available":     { fg: "#22C55E", bg: "rgba(34,197,94,0.12)"   },
  "protected":     { fg: "#A78BFA", bg: "rgba(167,139,250,0.14)" },
  "owner tool":    { fg: "#5EEAD4", bg: "rgba(94,234,212,0.12)"  },
  "draft":         { fg: "#94A3B8", bg: "rgba(148,163,184,0.18)" },
  "outlined":      { fg: "#7DD3FC", bg: "rgba(125,211,252,0.12)" },
  "operational":   { fg: "#22C55E", bg: "rgba(34,197,94,0.12)"   },
  "degraded":      { fg: "#EAB308", bg: "rgba(234,179,8,0.14)"   },
};
