create table if not exists public.project_blog_links (
  id bigint generated by default as identity primary key,
  project_id bigint not null
    references public.projects(id) on delete cascade,
  blog_post_id bigint not null
    references public.blog_posts(id) on delete cascade,
  created_at timestamptz not null
    default timezone('utc'::text, now()),
  unique (project_id, blog_post_id)
);

create index if not exists project_blog_links_project_id_idx
  on public.project_blog_links (project_id);

create index if not exists project_blog_links_blog_post_id_idx
  on public.project_blog_links (blog_post_id);

alter table public.project_blog_links enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'project_blog_links'
      and policyname = 'project_blog_links_read_all'
  ) then
    create policy "project_blog_links_read_all"
      on public.project_blog_links
      for select
      using (true);
  end if;
end
$$;
